### ISSUE TITLE
What is the username and password for logging in?

### ISSUE THREAD

**Issue by xunliu** [Netvariant/workflow-designer#1]
hi,

What is the username and password for logging in?
please tell me, Thanks!

**Comment by aabiabdallah** [comment]
Hello,

You can add the “MOQUI_WORKFLOW_API” artifact group to any existing Moqui user group and then use the credentials of any of the group members to login. 

Remember, this project depends on the Moqui component “moqui-workflow” found here:
https://github.com/Netvariant/moqui-workflow

**Comment by liuoomei** [comment]
hi，

This is cool, but now I just want to use the frontend of it, and the backend I'm going to use nodejs to complete it.Thank you very much for your selfless dedication.

**Comment by aabiabdallah** [comment]
Hello,

You free to use the frontend alone and integrate it with your project, but I'm afraid you'll have to dig into the code yourself to do the needful integrations. If you require our help you can drop us an email at hello@netvariant.com.
