### ISSUE TITLE
Proxy error: Could not proxy request /rest/s1/moqui-workflow/security/user/login from localhost:8081 to http://localhost:8080/ (ECONNREFUSED).

### ISSUE THREAD

**Issue by jahKIper** [Netvariant/workflow-designer#2]
1) What I need to do with Proxy error: Could not proxy request /rest/s1/moqui-workflow/security/user/login from localhost:8081 to http://localhost:8080/ (ECONNREFUSED). ?
2) How run it without autorization?
3) Can I got it like vue component, for including into my project?

**Comment by aabiabdallah** [comment]
Are you trying to use workflow-designer without a Moqui backend? The designer is tightly integrated with Moqui as of today. A standalone version can be done but it would require some work.

**Comment by jahKIper** [comment]
Yes, I'm trying to use workflow-designer without a Moqui backend
